Repository AY2324S2-CS2113-F14-2/tp, pull requests merged in 2024-03, with the labels that each got.

#30 Add more junit for parser
  src/test/java/ui/JunitParserTest.java
Labels: type.Chore, priority.Low

#31 Add and integrate logger for Menu class
  MenuLogger.log
  src/main/java/model/Menu.java
Labels: type.Chore

#40 Add method and command for displaying Menu
  src/test/java/model/MenuTest.java
Labels: priority.High

#57 Add model component to developer guide
  .gitignore
  MenuLogger.log
  MenuLogger.log.lck
  docs/DeveloperGuide.md
Labels: documentation

#58 Document model component and order logic in DG
  docs/DeveloperGuide.md
  docs/UMLdiagrams/model.puml
  docs/images/modelcomponent.png
Labels: documentation

#72 Modify Menu class, add MenuLogic
  src/main/java/command/MenuAddCommand.java
  src/main/java/command/MenuCommand.java
  src/main/java/command/MenuHelpCommand.java
  src/main/java/logic/MenuLogic.java
  src/main/java/model/Menu.java
  src/main/java/ui/CommandType.java
Labels: priority.High

#84 Implement Order.getReceipt method with discount
  src/main/java/model/Order.java
Labels: enhancement, priority.Low
