Repository AY2324S2-CS2113-F14-2/tp, pull requests merged in 2024-04, with the labels that each got.

#93 Add FAQ in the user guide
  docs/UserGuide.md
Labels: type.Chore

#145 Add Zhengwinter's PPP
  docs/team/zhengwinter.md
Labels: documentation

#144 Change receipt format
  .gitignore
  MenuLogger.log
  MenuLogger.log.lck
  OrderAddCommandLogger.log
  src/main/java/model/Order.java
Labels: enhancement

#143 Handle invalid inputs for restaurant details and order type
  src/main/java/logic/MainLogic.java
  src/main/java/logic/OrderLogic.java
Labels: bug

#146 Add storage feature for restaurant details, menus, and orders
  src/main/java/command/main/MainEditMenuCommand.java
  src/main/java/logic/MainLogic.java
  src/main/java/model/Order.java
  src/main/java/model/Restaurant.java
  src/main/java/storage/Storage.java
Labels: enhancement

#149 Storage.java: Handle NoSuchElement exception when reading save file
  src/main/java/storage/Storage.java
Labels: bug

#155 Added documentation for various commands
  src/main/java/command/main/MainCreateOrderCommand.java
  src/main/java/command/main/MainEditMenuCommand.java
  src/main/java/command/main/MainViewMenuCommand.java
  src/main/java/command/main/MainViewMenusSummaryCommand.java
  src/main/java/command/menu/MenuCompleteCommand.java
  src/main/java/command/menu/MenuExitCommand.java
  src/main/java/logic/MainLogic.java
  src/main/java/logic/MenuLogic.java
Labels: documentation

#156 Refactor code to remove unused token in initializeSystem in MainLogic
  .gitignore
  src/main/java/logic/MainLogic.java
Labels: type.Chore

#160 Add test case for menu commands and updated Zhengwinter's PPP
  docs/team/zhengwinter.md
  src/main/java/command/menu/MenuHelpCommand.java
  src/test/java/command/MenuCommandTest.java
  src/test/java/model/MenuTest.java
Labels: priority.Low

#161 Fix DG bugs based on review by TA
  docs/DeveloperGuide.md
  docs/UMLdiagrams/ArchitectureSequenceDiagram.puml
  docs/UMLdiagrams/OrderLogicSequenceDiagram.puml
  docs/UMLdiagrams/model.puml
  docs/UMLdiagrams/style.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/OrderLogicSequenceDiagram.png
  docs/images/modelcomponent.png
Labels: documentation

#184 Add test cases for all order commands
  MenuLogger.log.1
  OrderAddCommandLogger.log
  data/menus.txt
  src/main/java/command/order/OrderDeleteCommand.java
  src/test/java/command/MenuCommandTest.java
  src/test/java/command/OrderCommandTest.java
Labels: type.Chore

#186 Branch stats logic dg
  OrderAddCommandLogger.log
  data/menus.txt
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UMLdiagrams/StatsLogicSequenceDiagram.puml
  docs/UMLdiagrams/style.puml
  docs/images/StatsLogicSequenceDiagram.png
  src/main/java/command/order/OrderDeleteCommand.java
  src/main/java/logic/MainLogic.java
  src/main/java/logic/OrderLogic.java
Labels: documentation

#187 Update Zhengwinter's PPP
  docs/team/zhengwinter.md
Labels: documentation

#196 Update Zheqi's PPP
  docs/AboutUs.md
  docs/README.md
  docs/team/adamzzq.md
  docs/team/johndoe.md
Labels: documentation

#197 Branch more user stories
  docs/DeveloperGuide.md
Labels: documentation

#200 Edit UG and fix grammatical errors and formatting issues
  docs/UserGuide.md
Labels: type.Chore
